# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: my-pool

steps:
- checkout: self

- script: docker build -f $(System.DefaultWorkingDirectory)/Dockerfile . -t $(Docker_registry)/$(Image_name):$(Build.BuildNumber)
  displayName: 'build docker image'

- script: echo $Docker_Password | docker login -u chaitanya305 --password-stdin
  env:
    Docker_Password: $(Docker_pass)
  displayName: 'login to docker'

- script: docker push $(Docker_registry)/$(Image_name):$(Build.BuildNumber) 
  displayName: docker push

- script: docker run -p 80:80 -d --name energy-web $(Docker_registry)/$(Image_name):$(Build.BuildNumber)
  displayName: 'Running Container'