# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: my-pool

steps:
- checkout: self

- script: docker build $(System.DefaultWorkingDirectory)/Dockerfile -t $(Docker_registry)/$(Image_name):$(Build.BuildNumber)
  displayName: 'build docker image'

- script: $Docker_pass | docker login -u Chaitanya305 --password-stdin
  displayName: 'login to docker'

- script: docker push $(Docker_registry)/$(Image_name):$(Build.BuildNumber) 
  displayName: docker push