apiVersion: v1
kind: Pod
metadata: 
   name: pod
spec:
   containers:
      - name: container
        image: chaitanya305/demo-image:byme
        imagePullPolicy: IfNotPresent
        ports:
           - containerPort: 8000
